[database]
url = "localhost:6333"
collection-name = "default"

[embedding]
model-path = "openai/clip-vit-base-patch32"
device = "cpu"

[worker]
broker-url = "redis://localhost/0"
backend-url = "redis://localhost/1"
result-lifetime = "1d"