database:
  url: "localhost:6333"
  collection-name: "default"
embedding:
  model-path: "/home/stephan/KI-Modelle/clip-vit-large-patch14/"
  device: "cpu"
worker:
  broker-url: "redis://localhost/0"
  backend-url: "redis://localhost/1"
  result-lifetime: "1d"