version: '3.2'

services:
  api:
    image: python:3.11-slim
    container_name: image-search-api
    ports:
      - "8080:8080"
    links:
      - task_queue
      - qdrant
    networks:
      - text2image_search
  task_queue:
    image: python:3.11-slim
    container_name: task-queue
    links:
      - qdrant
      - redis
    networks:
      - text2image_search
  qdrant:
    image: qdrant/qdrant:v1.8.4
    container_name: vector-db
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant_data
    networks:
      - text2image_search
  redis:
    image: redis:7.2.4
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - text2image_search
configs:
  qdrant_config:
    content: |
      log_level: INFO
volumes:
  qdrant_storage:
networks:
  text2image_search: